name: Test

on:
  push:
    branches:
      - develop

jobs:

  setup-tests:
    runs-on: ubuntu-latest
    outputs:
      test-chunks: ${{ steps['set-test-chunks'].outputs['test-chunks'] }}
      test-chunk-ids: ${{ steps['set-test-chunk-ids'].outputs['test-chunk-ids'] }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - id: set-test-chunks
        name: Set Chunks
        run: echo test-chunks=$(npx jest --listTests --json | jq -cM '[_nwise(length / 2 | floor)]') >> $GITHUB_ENV

  run-all-tests:
    needs: [setup-tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunks: env.test-chunks
    steps:
      - uses: actions/checkout@v2
#      - run: npm install
      - run: echo ${{ matrix['chunks'] }}


#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: '12.x'
#
#      - name: 'Install dependencies'
#        run: npm ci
#
#      - name: 'Format'
#        run: npm run format
#
#      - name: 'Lint'
#        run: npm run lint
#
#      - name: 'Type check'
#        run: npm run build
#
#      - name: 'Test'
#        run: npm run test