name: Test

on:
  push:
    branches:
      - develop

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      test-chunks: ${{ steps['set-test-chunks'].outputs['test-chunks'] }}
      test-chunk-ids: ${{ steps['set-test-chunk-ids'].outputs['test-chunk-ids'] }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - id: set-test-chunks
        name: Set Chunks
        run: echo "::set-output name=test-chunks::$(npx jest --listTests --json | jq -cM '[_nwise(length / 2 | floor)]')"
      - id: set-test-chunk-ids
        name: Set Chunk IDs
        run: echo "::set-output name=test-chunk-ids::$(echo $CHUNKS | jq -cM 'to_entries | map(.key)')"
        env:
          CHUNKS: ${{ steps['set-test-chunks'].outputs['test-chunks'] }}
  test:
    runs-on: ubuntu-latest
    name: test (chunk ${{ matrix.chunk }})
    needs:
      - setup
    strategy:
      matrix:
        chunk: ${{ fromJson(needs.setup.outputs['test-chunk-ids']) }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: jest
        run: echo $CHUNKS | jq '.[${{ matrix.chunk }}] | .[] | @text' | xargs npx jest
        env:
          CHUNKS: ${{ needs.setup.outputs['test-chunks'] }}

#  setup-tests:
#    runs-on: ubuntu-latest
#    outputs:
#      test-chunks: ${{ steps['set-test-chunks'].outputs['test-chunks'] }}
#      test-chunk-ids: ${{ steps['set-test-chunk-ids'].outputs['test-chunk-ids'] }}
#    steps:
#      - uses: actions/checkout@v2
#      - run: npm install
#      - id: set-test-chunks
#        name: Set Chunks
#        run: echo 'TEST_CHUNKS=asdf' >> $GITHUB_ENV
#
#
#  run-all-tests:
#    needs: [setup-tests]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
##      - run: npm install
#      - run: echo $TEST_CHUNKS


#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: '12.x'
#
#      - name: 'Install dependencies'
#        run: npm ci
#
#      - name: 'Format'
#        run: npm run format
#
#      - name: 'Lint'
#        run: npm run lint
#
#      - name: 'Type check'
#        run: npm run build
#
#      - name: 'Test'
#        run: npm run test