name: Test

on:
  push:
    branches:
      - develop

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-file:
          - src/__tests__/binary
          - src/__tests__/bubble
          - src/__tests__/heap
          - src/__tests__/quick
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test -- ${{ matrix['test-file'] }}
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: '12.x'
#
#      - name: 'Install dependencies'
#        run: npm ci
#
#      - name: 'Format'
#        run: npm run format
#
#      - name: 'Lint'
#        run: npm run lint
#
#      - name: 'Type check'
#        run: npm run build
#
#      - name: 'Test'
#        run: npm run test